Added implementation of GetArea() and GetPerimeter() methods, added implementation for Circle.
trol80lvl2/Project1 pull request #1
Opened 2021-01-14 20:36 UTC by trol80lvl2

Added implementation of GetArea() and GetPerimeter() methods, added implementation for Circle.

2021-01-14 20:49 UTC, Vadimur requested changes

2021-01-14 20:49 UTC, Vadimur commented on ConsoleShapes/Circle.cs
> +        }
Ці два методи дублюють геттери властивостей S і P. Можна зробити публічний геттер і протектед сеттер для цих властивостей.

2021-01-14 20:49 UTC, Vadimur commented on ConsoleShapes/Shape.cs
> +        public abstract int Depth { get; set; }
Тут точно потрібнен модифікатор abstract?

2021-01-15 10:44 UTC, trol80lvl2 commented on ConsoleShapes/Circle.cs
> +        }
Виправлено

2021-01-15 11:35 UTC, merged